// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    throw UnsupportedError('Platform not supported');
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnoBWmYeMAUF1X6Rg2NRTgWzdVSLowaro',
    authDomain: 'kelegance.firebaseapp.com',
    projectId: 'kelegance',
    storageBucket: 'kelegance.firebasestorage.app',
    messagingSenderId: '766009026310',
    appId: '1:766009026310:web:e7e3e6c8fa24cd2d8a6087',
    measurementId: 'G-5Z74K3NM09',
  );
}
