// File generated by FlutterFire CLI.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    throw UnsupportedError('Platform not supported');
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'METS_TON_ANCIENNE_API_KEY_ICI',
    authDomain: 'kelegance-vtc.firebaseapp.com',
    projectId: 'kelegance-vtc',
    storageBucket: 'kelegance-vtc.appspot.com',
    messagingSenderId: 'METS_TON_ANCIEN_SENDER_ID_ICI',
    appId: 'METS_TON_ANCIEN_APP_ID_ICI',
  );
}